# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Holler
email: nick@holler.com
description: Holler is the mobile customer support and communication platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.holler.com/" # the base hostname & protocol for your site
twitter_username: holler
permalink: pretty

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
